service:
  name: data-export-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

custom:
  serverless-offline:   ## add this two lines
      port: 4000        ## bellow "custom:" line

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: export
