service:
  name: data-export-scheduler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

# serverless offline config
custom:
  config: ${file(config.json)}
  app-name: ${self:custom.config.appName}
  serverless-offline:
      port: 4000
      babelOptions:
        presets: ["es2015"]
  dynamodb:
    stages:
      - ${self:custom.config.stage}
    start:
      migrate: true
  s3Buckets:
    BUCKET_NAME: ${self:custom.app-name}-${self:service}-${self:custom.config.stage}-exports-bucket
    
provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.config.region}
  environment:
    REGION: ${self:custom.config.region}
    STAGE: ${self:custom.config.stage}
    APP_NAME: ${self:custom.config.appName}
    DYNAMODB_TABLE: ${self:custom.app-name}-${self:service}-${self:custom.config.stage}
    EMAIL_RECEIVERS: ${self:custom.config.emailReceivers}
    EMAIL_SENDER: ${self:custom.config.emailSender}
    SEGMENT_EXCLUDED_TOPICS: ${self:custom.config.segmentExcludedTopics}
    AMPLITUDE_EXCLUDED_TOPICS: ${self:custom.config.amplitudeExcludedTopics}
    EXPORT_SERVICES: ${self:custom.config.services}
    TEMPLATES_BUCKET: ${self:custom.config.templatesBucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
        - ses:SendEmail
        - secretsmanager:GetSecretValue
        - s3:*
      Resource: 
        - "arn:aws:dynamodb:${self:custom.config.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${self:custom.config.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
        - "arn:aws:lambda:${self:custom.config.region}:*:function:*"
        - "arn:aws:ses:${self:custom.config.region}:*"
        - "arn:aws:ses:${self:custom.config.region}:*:identity/*"
        - "arn:aws:secretsmanager:${self:custom.config.region}:*"
        - "arn:aws:s3:::${self:provider.environment.TEMPLATES_BUCKET}/*"
        - "arn:aws:s3:::${self:custom.s3Buckets.BUCKET_NAME}/*"
        - "arn:aws:s3:::${self:custom.s3Buckets.BUCKET_NAME}"
        - "arn:aws:s3:::${self:provider.environment.TEMPLATES_BUCKET}"
        - "arn:aws:logs:${self:custom.config.region}:*:log-group:*"
        - "arn:aws:logs:${self:custom.config.region}:*:log-group:*:*:*"

functions:
  start:
    handler: handlers/StartExports.run
    timeout: 120
          
  download:
    handler: handlers/CheckDownloads.run
    timeout: 120
    environment:
      FUNCTION_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
      EXPORTS_BUCKET: ${self:custom.s3Buckets.BUCKET_NAME}

  copy:
    handler: handlers/CopyFile.run

  status:
    handler: handlers/CheckStatus.run
    timeout: 30
    events:
      - http:
          method: get
          path: status

  transform:
    handler: handlers/Transform.run
    timeout: 120
    environment:
      FUNCTION_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    events:
      - s3:
        bucket: ${self:custom.s3Buckets.BUCKET_NAME}
        event: s3:ObjectCreated:*
        existing: true
  
  report:
    handler: handlers/JobReport.run
    timeout: 120

  # testTransform:
  #   handler: handlers/TestTransform.run
  #   events:
  #     - http:
  #         method: post
  #         path: test

resources:
  Resources:
    ExportDB:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: downloadPath
            AttributeType: S
          - AttributeName: downloaded
            AttributeType: S
        KeySchema:
          - AttributeName: downloadPath
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: DownloadedIndex
            KeySchema:
              - AttributeName: downloaded
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    S3BucketExportTransforms:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:custom.s3Buckets.BUCKET_NAME}'
        LifecycleConfiguration: 
          Rules:
              - Id: DeleteEverythingInSevenDays
                Prefix: ''
                Status: Enabled
                ExpirationInDays: 7
    TransformLambdaPermissionS3:
      Type: 'AWS::Lambda::Permission'
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - TransformLambdaFunction
            - Arn
        Principal: 's3.amazonaws.com'
        Action: 'lambda:InvokeFunction'
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: 'arn:aws:s3:::${self:custom.s3Buckets.BUCKET_NAME}'