service:
  name: data-export-scheduler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

# serverless offline config
custom:
  serverless-offline:
      port: 4000
      babelOptions:
        presets: ["es2015"]
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
  s3Buckets:
    BUCKET_NAME: ${self:service}-${opt:stage, self:provider.stage}-exports-bucket
    
provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    BRANCH_KEY: add_here
    BRANCH_SECRET: add_here
    ACCESS_KEY_ID: add_here
    ACCESS_SECRET_KEY: add_here
    SERVICE_TYPE: Branch
    SEGMENT_WRITE_KEY: add_here
    TEMPLATES_BUCKET: data-export-lambda-templates
    REPORT_RECEIVER_MAIL: add_report_receivers_separated_by_commas
    REPORT_SENDER_MAIL: add_sender_email
    EXPORT_SERVICES: Segment # Options are Segment, Mixpanel, Amplitude for now
    EXCLUDED_TOPICS: Click # These files will get ignored from uploading. See Models.ts - ExcludedType for options
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:lambda:${opt:region, self:provider.region}:*:*"
        - "arn:aws:s3:::${self:custom.s3Buckets.BUCKET_NAME}"
        - "arn:aws:ses:${opt:region, self:provider.region}:*"

functions:
  start:
    handler: handlers/StartExports.run
          
  download:
    handler: handlers/CheckDownloads.run
    environment:
      FUNCTION_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
      EXPORTS_BUCKET: ${self:custom.s3Buckets.BUCKET_NAME}
    events:
      - http:
          method: get
          path: download

  copy:
    handler: handlers/CopyFile.run

  status:
    handler: handlers/CheckStatus.run
    events:
      - http:
          method: get
          path: status

  transform:
    handler: handlers/Transform.run
    environment:
      FUNCTION_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    events:
      - s3:
        bucket: ${self:custom.s3Buckets.BUCKET_NAME}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .csv
        existing: true
  
  report:
    handler: handlers/JobReport.run

  # testTransform:
  #   handler: handlers/TestTransform.run
  #   events:
  #     - http:
  #         method: post
  #         path: test

resources:
  Resources:
    ExportDB:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: downloadPath
            AttributeType: S
          - AttributeName: downloaded
            AttributeType: S
        KeySchema:
          - AttributeName: downloadPath
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: DownloadedIndex
            KeySchema:
              - AttributeName: downloaded
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    S3BucketExportTransforms:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:custom.s3Buckets.BUCKET_NAME}'
    TransformLambdaPermissionS3:
      Type: 'AWS::Lambda::Permission'
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - TransformLambdaFunction
            - Arn
        Principal: 's3.amazonaws.com'
        Action: 'lambda:InvokeFunction'
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: 'arn:aws:s3:::${self:custom.s3Buckets.BUCKET_NAME}'