import BranchEvent from '../src/model/BranchEvent'
import { ExportService } from '../src/model/Models'

export const testEvent: BranchEvent = {
  exportService: ExportService.None,
  "id": 685102994546689427,
  "name": "PURCHASE",
  "timestamp": 1564579508998,
  "timestamp_iso": "2019-07-31 13:25:08+0000",
  "origin": "BRANCH",
  "last_attributed_touch_type": "CLICK",
  "last_attributed_touch_timestamp": "1564579501000",
  "last_attributed_touch_timestamp_iso": "2019-07-31 13:25:01+0000",
  "last_attributed_touch_data_tilde_id": "",
  "last_attributed_touch_data_tilde_campaign": "Top vs Bottom Banner A/B Test",
  "last_attributed_touch_data_tilde_campaign_id": "lksjdfosijosidjfosidjf",
  "last_attributed_touch_data_tilde_channel": "Some Channel",
  "last_attributed_touch_data_tilde_feature": "journeys",
  "last_attributed_touch_data_tilde_stage": "Some Stage",
  "last_attributed_touch_data_tilde_tags": "[\"Bottom Banner\",\"An awesome banner\",\"Somewhere on this webpage\"]",
  "last_attributed_touch_data_tilde_advertising_partner_name": "",
  "last_attributed_touch_data_tilde_secondary_publisher": "",
  "last_attributed_touch_data_tilde_creative_name": "",
  "last_attributed_touch_data_tilde_creative_id": "",
  "last_attributed_touch_data_tilde_ad_set_name": "",
  "last_attributed_touch_data_tilde_ad_set_id": "",
  "last_attributed_touch_data_tilde_ad_name": "",
  "last_attributed_touch_data_tilde_ad_id": "",
  "last_attributed_touch_data_tilde_branch_ad_format": "",
  "last_attributed_touch_data_tilde_technology_partner": "",
  "last_attributed_touch_data_tilde_banner_dimensions": "",
  "last_attributed_touch_data_tilde_placement": "",
  "last_attributed_touch_data_tilde_keyword_id": "",
  "last_attributed_touch_data_tilde_agency": "",
  "last_attributed_touch_data_tilde_optimization_model": "",
  "last_attributed_touch_data_tilde_secondary_ad_format": "",
  "last_attributed_touch_data_tilde_journey_name": "Top vs Bottom Banner A/B Test",
  "last_attributed_touch_data_tilde_journey_id": "5bfc84012503fecd2e596f25",
  "last_attributed_touch_data_tilde_view_name": "Bottom Banner",
  "last_attributed_touch_data_tilde_view_id": "595747715178848265",
  "last_attributed_touch_data_plus_current_feature": "",
  "last_attributed_touch_data_plus_via_features": "[\"Homepage Feature\", \"Another feature\", \"One more feature\"]",
  "last_attributed_touch_data_dollar_3p": "",
  "last_attributed_touch_data_plus_web_format": "",
  "last_attributed_touch_data_tilde_customer_campaign": "", 
  "last_attributed_touch_data_tilde_campaign_type": "", 
  "last_attributed_touch_data_tilde_agency_id": "", 
  "last_attributed_touch_data_plus_touch_id": "", 

  "last_attributed_touch_data_custom_fields": "{\"$og_title\":\"Journeys Commerce Events\",\"+url\":\"https:\\/\\/branch-demo.app.link\\/09wURzIDbW\",\"~creation_source\":5,\"$og_description\":\"QA Tests for Commerce v2 Events\",\"$og_video\":\"http:\\/\\/qaauto.branch.io\\/video\",\"$one_time_use\":false,\"$canonical_url\":\"http:\\/\\/qaauto.branch.io\\/qa\\/test_cases\\/journey_banner20.html?branch_key=key_live_kkGffiMKsmMX4B5umosCzlkduueBt6qZ\",\"$uri_redirect_mode\":1,\"$og_image_url\":\"http:\\/\\/branch.io\\/img\\/logo_icon_black.png\"}",

  "days_from_last_attributed_touch_to_event": "0",
  "hours_from_last_attributed_touch_to_event": "",
  "minutes_from_last_attributed_touch_to_event": "",
  "seconds_from_last_attributed_touch_to_event": "",
  "last_cta_view_timestamp": "1559389564000",
  "last_cta_view_timestamp_iso": "2019-06-01 11:46:04+0000",
  "last_cta_view_data_tilde_id": "",
  "last_cta_view_data_tilde_campaign": "",
  "last_cta_view_data_tilde_campaign_id": "",
  "last_cta_view_data_tilde_channel": "",
  "last_cta_view_data_tilde_feature": "",
  "last_cta_view_data_tilde_stage": "",
  "last_cta_view_data_tilde_tags": "[]",
  "last_cta_view_data_tilde_advertising_partner_name": "",
  "last_cta_view_data_tilde_secondary_publisher": "",
  "last_cta_view_data_tilde_creative_name": "",
  "last_cta_view_data_tilde_creative_id": "",
  "last_cta_view_data_tilde_ad_set_name": "",
  "last_cta_view_data_tilde_ad_set_id": "",
  "last_cta_view_data_tilde_ad_name": "",
  "last_cta_view_data_tilde_ad_id": "",
  "last_cta_view_data_tilde_branch_ad_format": "",
  "last_cta_view_data_tilde_technology_partner": "",
  "last_cta_view_data_tilde_banner_dimensions": "",
  "last_cta_view_data_tilde_placement": "",
  "last_cta_view_data_tilde_keyword_id": "",
  "last_cta_view_data_tilde_agency": "",
  "last_cta_view_data_tilde_optimization_model": "",
  "last_cta_view_data_tilde_secondary_ad_format": "",
  "last_cta_view_data_plus_via_features": "[]",
  "last_cta_view_data_dollar_3p": "",
  "last_cta_view_data_plus_web_format": "",
  "last_cta_view_data_custom_fields": "",
  "deep_linked": "false",
  "first_event_for_user": "false",
  "user_data_os": "ANDROID",
  "user_data_os_version": "26",
  "user_data_model": "Pixel",
  "user_data_browser": "Chrome",
  "user_data_geo_country_code": "US",
  "user_data_app_version": "5.12.1",
  "user_data_sdk_version": "3.0.4",
  "user_data_geo_dma_code": 807,
  "user_data_environment": "FULL_APP",
  "user_data_platform": "ANDROID_APP",
  "user_data_aaid": "2f3ff5df-fd74-0bfa-1286-70755d580118",
  "user_data_idfa": "",
  "user_data_idfv": "",
  "user_data_android_id": "",
  "user_data_limit_ad_tracking": "false",
  "user_data_user_agent": "Mozilla/5.0 (Linux; Android 8.0.0; Pixel Build/OPR3.170623.008) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36",
  "user_data_ip": "54.183.153.61",
  "user_data_developer_identity": "someidentity@identity.com",
  "user_data_language": "EN",
  "user_data_brand": "Google",
  "di_match_click_token": 100,
  "event_data_revenue_in_usd": "100.0",
  "event_data_exchange_rate": "1.0",
  "event_data_transaction_id": "",
  "event_data_revenue": "100.0",
  "event_data_currency": "USD",
  "event_data_shipping": "",
  "event_data_tax": "",
  "event_data_coupon": "",
  "event_data_affiliation": "",
  "event_data_search_query": "",
  "event_data_description": "",
  "event_timestamp": 1564579508998,
  "custom_data": "{\"$amplitude_user_id\":\"amplitude_identity\"}",
  "last_attributed_touch_data_tilde_keyword": "",
  "user_data_cross_platform_id": "",
  "user_data_past_cross_platform_ids": "[]",
  "user_data_prob_cross_platform_ids": "[]",
  "store_install_begin_timestamp": "",
  "referrer_click_timestamp": "",
  "user_data_os_version_android": "",
  "user_data_geo_city_code": 5392171,
  "user_data_geo_city_en": "San Jose",
  "user_data_http_referrer": "",
  "hash_version": "UNHASHED",
  "customer_event_alias": "", 
  "last_cta_view_data_tilde_campaign_type": "",
  "last_cta_view_data_plus_touch_id" :"", 
  "user_data_installer_package_name" : "",
  "user_data_cpu_type": "", 
  "user_data_screen_width": 720, 
  "user_data_screen_height": 1024, 
  "user_data_build": "",
  "user_data_internet_connection_type": ""
}